import lgsvl
import os

# Simulation Configuration
SIMULATOR_HOST = "localhost"
BRIDGE_HOST = "localhost"
MAP = "BorregasAve"

# Scenario Configuration
# EGO
EGO_INITIAL_SPEED = 20
EGO_DISTANCE_TO_INTERSECTION = 50

# AGENT 1
AGENT_1_INITIAL_DISTANCE_TO_INTERSECTION = 50
AGENT_1_INITIAL_SPEED = 20
AGENT_1_SPEED_INTERSECTION_APPROACH = 20
AGENT_1_SPEED_INSIDE_INTERSECTION_ = 10
AGENT_1_LATERAL_POSITION_INITIAL = 0
AGENT_1_LATERAL_POSITION_INSIDE_INTERSECTION = 0
AGENT_1_LATERAL_POSITION_INTERSECTION_APPROACH = 0

# AGENT 2
AGENT_2_LATERAL_POSITION_INITIAL = 0
AGENT_2_INITIAL_SPEED = 20
AGENT_2_DISTANCE_TO_INTERSECTION = 50

# Connect to simulator
sim = lgsvl.Simulator(os.environ.get("SIMULATOR_HOST", "127.0.0.1"), 8181)

# Set the map scene
if sim.current_scene == MAP:
    sim.reset()
else:
    sim.load(MAP)
